# Generated by Django 5.0.2 on 2024-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_remove_student_course_key'),
    ]
