# Generated by Django 5.0.2 on 2024-03-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0008_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='Class Work', max_length=255),
        ),
    ]
